kind: pipeline
name: default

platform:
    os: linux
    arch: amd64

steps:
    - name: build_test
      image: node:12
      environment:
          CODECOV_TOKEN:
              from_secret: CODECOV_TOKEN
          SOL_AST_COMPILER_CACHE: /.compiler_cache
      commands:
          - ./docker/download.sh
          - npm install --unsafe-perm
          - npm link --unsafe-perm
          - npm run lint
          - npm test
          - npm run coverage:upload
