kind: pipeline
name: default

platform:
    os: linux
    arch: amd64

steps:
    - name: build_test
      image: node:12
      environment:
          CODECOV_TOKEN:
              from_secret: CODECOV_TOKEN
          SOL_AST_COMPILER_CACHE: /.compiler_cache
      commands:
          # pre-download native compilers
          - apt-get -qq update && apt-get -qq install jq
          - ./docker/download.sh 'linux-amd64'
          # remove list and one rarely used compiler to still test downloading on-demand
          - rm /.compiler_cache/linux-amd64/list.json
          - rm /.compiler_cache/linux-amd64/solc-linux-amd64-v0.5.17+commit.d19bba13
          # perform testing
          - npm install --unsafe-perm
          - npm link --unsafe-perm
          - npm run lint
          - npm test
          - npm run coverage:upload
